version: '3'
services:
  rg2:
    build: .
    image: 3jackdaws/resume:v3
    environment:
      - HOST=0.0.0.0
    ports:
      - 3000:3000
    volumes:
      - resumes:/resumes

  vscode:
    image: codercom/code-server
    command: --auth none
    volumes:
      - resumes:/home/coder/project/resumes
    ports:
      - 8080:8080

volumes:
  resumes:
